version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - satackey
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: pikepdf
    versions:
    - 2.10.0
    - 2.11.0
    - 2.5.0
    - 2.7.0
    - 2.8.0
    - 2.8.0.post1
    - 2.8.0.post2
    - 2.9.0
    - 2.9.1
    - 2.9.2
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
